// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUcF0ePfaj2oMSabh0ETUzg0_zArFsCmA',
    appId: '1:687663433325:web:05f13545829ff8147ce164',
    messagingSenderId: '687663433325',
    projectId: 'tutiendaapp-1efb8',
    authDomain: 'tutiendaapp-1efb8.firebaseapp.com',
    storageBucket: 'tutiendaapp-1efb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHt_qTtjA1hZ33bfBO4RjC3LtMJEr3wIc',
    appId: '1:687663433325:ios:fa1be2d562c872097ce164',
    messagingSenderId: '687663433325',
    projectId: 'tutiendaapp-1efb8',
    storageBucket: 'tutiendaapp-1efb8.firebasestorage.app',
    iosBundleId: 'com.example.tuTienda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHt_qTtjA1hZ33bfBO4RjC3LtMJEr3wIc',
    appId: '1:687663433325:ios:fa1be2d562c872097ce164',
    messagingSenderId: '687663433325',
    projectId: 'tutiendaapp-1efb8',
    storageBucket: 'tutiendaapp-1efb8.firebasestorage.app',
    iosBundleId: 'com.example.tuTienda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUcF0ePfaj2oMSabh0ETUzg0_zArFsCmA',
    appId: '1:687663433325:web:86f716a077d659e77ce164',
    messagingSenderId: '687663433325',
    projectId: 'tutiendaapp-1efb8',
    authDomain: 'tutiendaapp-1efb8.firebaseapp.com',
    storageBucket: 'tutiendaapp-1efb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-wvh7Awz8wjHFPSt4vi33qD6DYbIwK2M',
    appId: '1:687663433325:android:a2384285a4e5adcb7ce164',
    messagingSenderId: '687663433325',
    projectId: 'tutiendaapp-1efb8',
    storageBucket: 'tutiendaapp-1efb8.firebasestorage.app',
  );

}